[package]
name = "cellium-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cellium-core.workspace = true
serde.workspace = true
taffy.workspace = true
thiserror.workspace = true
unicode-segmentation.workspace = true
winit.workspace = true

[lints]
workspace = true
